services:
  mongodb:
    image: mongo:8-noble
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: minisocialdb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - reactive-ms-network

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - reactive-ms-network

volumes:
  mongo_data:
  redis_data:

networks:
  reactive-ms-network:
    external: true