services:
  cassandra:
    image: cassandra:5-jammy
    container_name: cassandra
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    ports:
      - 9042:9042
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./cassandra:/scripts
    networks:
      - reactive-ms-network

  mongodb:
    image: mongo:8-noble
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: minisocialdb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - reactive-ms-network

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - reactive-ms-network

volumes:
  cassandra_data:
  mongo_data:
  redis_data:

networks:
  reactive-ms-network:
    external: true